### ISSUE TITLE
How to derive 3D Bounding Box in TransVG + backproj methods in your paper?

### ISSUE THREAD

**Issue by yfthu** [ZhanYang-nwpu/Mono3DVG#11]
![image](https://github.com/ZhanYang-nwpu/Mono3DVG/assets/44047538/a60944fa-a41f-4591-962a-3ca91d19e787)
Hello, thank you for your work.
In your paper, you provide many 2D grounding + backproj methods as baselines, such as ReSC + backproj, TransVG + backproj. 
I would like to know how to derive 3D bounding boxes in these 2D grounding + backproj methods. 
Do you predict depth in these 2D grounding + backproj methods?
What depth do you use when you conduct back projection?
Thank you very much!

**Comment by yfthu** [comment]
@ZhanYang-nwpu

**Comment by ZhanYang-nwpu** [comment]
> ![image](https://private-user-images.githubusercontent.com/44047538/347440728-a60944fa-a41f-4591-962a-3ca91d19e787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzI5MDgsIm5iZiI6MTcyMTAzMjYwOCwicGF0aCI6Ii80NDA0NzUzOC8zNDc0NDA3MjgtYTYwOTQ0ZmEtYTQxZi00NTkxLTk2MmEtM2NhOTFkMTllNzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMTlmZDEzMTJiNGZlNDBhYmQ2NDBkZWE4MTU0NzgyMTBhNzIwNzBmNjMzMDkxNDk4ODVkOGVmNjgzNTU5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OiAfdSDlSlCyhgO0w5L9JPqtjXmS6ziR_O8qgZBEdIk) Hello, thank you for your work. In your paper, you provide many 2D grounding + backproj methods as baselines, such as ReSC + backproj, TransVG + backproj. I would like to know how to derive 3D bounding boxes in these 2D grounding + backproj methods. Do you predict depth in these 2D grounding + backproj methods? What depth do you use when you conduct back projection? Thank you very much!



The back projection follows the paper ScanRefer. 
This operation uses depth information to project 2D bounding boxes into 3D space. 
The depth information comes directly from the ground truth in the KITTI's point cloud data.

**Comment by yfthu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/44047538/347440728-a60944fa-a41f-4591-962a-3ca91d19e787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzI5MDgsIm5iZiI6MTcyMTAzMjYwOCwicGF0aCI6Ii80NDA0NzUzOC8zNDc0NDA3MjgtYTYwOTQ0ZmEtYTQxZi00NTkxLTk2MmEtM2NhOTFkMTllNzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMTlmZDEzMTJiNGZlNDBhYmQ2NDBkZWE4MTU0NzgyMTBhNzIwNzBmNjMzMDkxNDk4ODVkOGVmNjgzNTU5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OiAfdSDlSlCyhgO0w5L9JPqtjXmS6ziR_O8qgZBEdIk) Hello, thank you for your work. In your paper, you provide many 2D grounding + backproj methods as baselines, such as ReSC + backproj, TransVG + backproj. I would like to know how to derive 3D bounding boxes in these 2D grounding + backproj methods. Do you predict depth in these 2D grounding + backproj methods? What depth do you use when you conduct back projection? Thank you very much!
> 
> The back projection follows the paper ScanRefer. This operation uses depth information to project 2D bounding boxes into 3D space. The depth information comes directly from the ground truth in the KITTI's point cloud data.

Thank you very much for your answer!
