### ISSUE TITLE
code and dataset release

### ISSUE THREAD

**Issue by yfthu** [ZhanYang-nwpu/Mono3DVG#2]
Dear Dr. Yang Zhan: 

Thank you very much for your excellent work! You said "The dataset and code will be released." in your AAAI24 paper. May I ask when will the code and dataset be released? 

Thank you very much!

**Comment by ZhanYang-nwpu** [comment]
Thank you for reaching out and for your interest in our work.

Our dataset has already been open-sourced last year, and you can find more information in the README.md. 
As for the code, we are currently in the process of organizing it. As soon as the code is ready, we will release it promptly.

Thank you for your patience and understanding.

Best regards,
Zhan

**Comment by ZhanYang-nwpu** [comment]
Code, checkpoints, and dataset have all been released.
