### ISSUE TITLE
Thank your great work! When will the code be released?

### ISSUE THREAD

**Issue by drilistbox** [ZhanYang-nwpu/Mono3DVG#3]

**Comment by ZhanYang-nwpu** [comment]
Thank you for reaching out and for your interest in our work.

We are currently in the process of organizing the code. As soon as the code is ready, we will release it promptly.
It is expected to be finished in two weeks.

Thank you for your patience and understanding.

Best regards,
Zhan

**Comment by ZhanYang-nwpu** [comment]
> _No description provided._

Code, checkpoints, and dataset have all been released.
