### ISSUE TITLE
About retest record

### ISSUE THREAD

**Issue by jjlinghu** [ZhanYang-nwpu/Mono3DVG#4]
Thanks to the authors for releasing the code quickly! I have retested the code and completely repeated the performance that the author declares in the paper.
![image](https://github.com/ZhanYang-nwpu/Mono3DVG/assets/54942065/62c7f165-9efe-4d27-876a-5dfbe64a5802)

There are a few things to note:
1. When I load the pre_trained model `checkpoint_best.pth`, 
https://github.com/ZhanYang-nwpu/Mono3DVG/blob/da207e5bf216b707370a5175133e11e6614c4d30/lib/helpers/save_helper.py#L80
 I miss the _RuntimeError: Unexpected key(s) in state_dict: "text_encoder.embeddings.position_ids"_. By carefully comparing the model and the weight parameters, I didn't see any difference. This phenomenon makes me confused. Anyway, I solved this issue by setting `strict=False` and it can't decline the performance.
3. Some `np.float`, and `np.bool` need to be changed to  `np.float64`, and `np.bool_` if the version of NumPy > 1.20
4. It seems that not only MonoRefer dataset is used, we may utilize the raw `KITTI/training/calib` by soft link.
https://github.com/ZhanYang-nwpu/Mono3DVG/blob/da207e5bf216b707370a5175133e11e6614c4d30/lib/datasets/mono3drefer/mono3drefer_dataset.py#L68
5. The file path may need to be modified appropriately.

Thanks to the authors for their contributions to the community!

**Comment by ZhanYang-nwpu** [comment]
> Thanks to the authors for releasing the code quickly! I have retested the code and completely repeated the performance that the author declares in the paper. ![image](https://private-user-images.githubusercontent.com/54942065/312690479-62c7f165-9efe-4d27-876a-5dfbe64a5802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTMzMjQsIm5iZiI6MTcxMDM5MzAyNCwicGF0aCI6Ii81NDk0MjA2NS8zMTI2OTA0NzktNjJjN2YxNjUtOWVmZS00ZDI3LTg3NmEtNWRmYmU2NGE1ODAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA1MTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZmJiM2ViODVjNGRkOGM4ZGE3MWNmMTMxN2I2MjA5N2RkNzczOWNkMTExMmQ1ZjE2MDRkZTJiYmEwNzBlNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WSG0T5t70Vqgnni0bU1dp-5Kgz9Fq9hPj7J8K-ZfN-o)
> 
> There are a few things to note:
> 
> 1. When I load the pre_trained model `checkpoint_best.pth`,
>    https://github.com/ZhanYang-nwpu/Mono3DVG/blob/da207e5bf216b707370a5175133e11e6614c4d30/lib/helpers/save_helper.py#L80
>    
>    I miss the _RuntimeError: Unexpected key(s) in state_dict: "text_encoder.embeddings.position_ids"_. By carefully comparing the model and the weight parameters, I didn't see any difference. This phenomenon makes me confused. Anyway, I solved this issue by setting `strict=False` and it can't decline the performance.
> 2. Some `np.float`, and `np.bool` need to be changed to  `np.float64`, and `np.bool_` if the version of NumPy > 1.20
> 3. It seems that not only MonoRefer dataset is used, we may utilize the raw `KITTI/training/calib` by soft link.
>    https://github.com/ZhanYang-nwpu/Mono3DVG/blob/da207e5bf216b707370a5175133e11e6614c4d30/lib/datasets/mono3drefer/mono3drefer_dataset.py#L68
> 4. The file path may need to be modified appropriately.
> 
> Thanks to the authors for their contributions to the community!



I have a lot of things going on recently so I'm in a hurry to organize the code. Thank you very much for reminding me. I will check the code again.

**Comment by ZhanYang-nwpu** [comment]
1. Yes, you are right. We need to set strict=False, it won't affect anything.
2. My Numpy version is 1.23.4, so I don't have this problem.
3. Our mono3drefer_dataset.py does have a channel for calib data loading. We need to use a camera calibration parameter calib.P2. I have now solved the problem and uploaded our calib.zip in Mono3DRefer folder.

**Comment by jjlinghu** [comment]
It seems that the [Pre-trained model (MonoDETR)](https://drive.google.com/file/d/1RkmgkT0R29rF3-8R9BmLIe-H69Kf3o1d/view) is destroyed when uploads.

**Comment by ZhanYang-nwpu** [comment]
> It seems that the [Pre-trained model (MonoDETR)](https://drive.google.com/file/d/1RkmgkT0R29rF3-8R9BmLIe-H69Kf3o1d/view) is destroyed when uploads.

Yes, it could be because of the network. I'll fix this right now.

**Comment by ZhanYang-nwpu** [comment]
> It seems that the [Pre-trained model (MonoDETR)](https://drive.google.com/file/d/1RkmgkT0R29rF3-8R9BmLIe-H69Kf3o1d/view) is destroyed when uploads.

This issue has been resolved.
