### ISSUE TITLE
感谢作者开源代码，但是按CUDA_VISIBLE_DEVICES=1 python train.py复现掉3-5点，请教下想复现出原始论文中的结果需要怎么个配置呢

### ISSUE THREAD

**Issue by drilistbox** [ZhanYang-nwpu/Mono3DVG#7]

**Comment by ZhanYang-nwpu** [comment]
> _No description provided._

你好，公布的模型代码和参数并没有问题，你训练的过程也没有问题。
我最近经过实验发现，每一次训练模型的初始化参数会存在极其微小的差异，导致每次训练的过程和结果都无法再次复刻。
我会尽快解决该问题。我们已经公开了checkpoint给大家直接测试模型提供方便。

详情请参考 #6
