### ISSUE TITLE
The rotation error is not considered when calculating IoU in evaluation

### ISSUE THREAD

**Issue by yfthu** [ZhanYang-nwpu/Mono3DVG#9]
Thank you for your excellent work!

In your code, when evaluating, the IoU calculating is in lib\helpers\tester_helper.py: 213. The calc_iou function is in lib\helpers\utils_helper.py. The calc_iou computes the IoU of two axis-aligned boxes.

 
![image](https://github.com/ZhanYang-nwpu/Mono3DVG/assets/44047538/16f9c7ed-c274-40e6-af81-2a5e2b834602)

![image](https://github.com/ZhanYang-nwpu/Mono3DVG/assets/44047538/9f00e5c1-a40d-4fe3-a4fe-e46e39ebbff7)

 
However, your code does not consider the rotation difference between two bounding boxes. That is, when calculating IoU, your code assumes the predicted rotation is the same as the ground truth.

I wonder why the rotation error could be ignored when calculating IoU in evaluation. Thank you very much!

**Comment by yfthu** [comment]
@ZhanYang-nwpu

**Comment by ZhanYang-nwpu** [comment]
> Thank you for your excellent work!
> 
> In your code, when evaluating, the IoU calculating is in lib\helpers\tester_helper.py: 213. The calc_iou function is in lib\helpers\utils_helper.py. The calc_iou computes the IoU of two axis-aligned boxes.
> 
> ![image](https://private-user-images.githubusercontent.com/44047538/336096087-16f9c7ed-c274-40e6-af81-2a5e2b834602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjgxODQsIm5iZiI6MTcxODMyNzg4NCwicGF0aCI6Ii80NDA0NzUzOC8zMzYwOTYwODctMTZmOWM3ZWQtYzI3NC00MGU2LWFmODEtMmE1ZTJiODM0NjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2M2Y3NzVhN2U5YTQ2NWM4MmViMzI3NTliYTE2NjllZWM4MzE4NGE2ZDZkMmU5YWRiZTIyNDI1Y2ZkMDkzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-YVMGQEMJNREypNMPG2_WrWL0_cho6DY1gVPZ1VdmrM)
> 
> ![image](https://private-user-images.githubusercontent.com/44047538/336095745-9f00e5c1-a40d-4fe3-a4fe-e46e39ebbff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjgxODQsIm5iZiI6MTcxODMyNzg4NCwicGF0aCI6Ii80NDA0NzUzOC8zMzYwOTU3NDUtOWYwMGU1YzEtYTQwZC00ZmUzLWE0ZmUtZTQ2ZTM5ZWJiZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGRjNjZhYTA4YzRlNzg5NGFkMGE2OTIwMDc5ODE0ZGRmNjQzZGFhNjE4ZWRlYWY4M2Y2Nzk4ODkyZGYxNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_09xSdVraMkEz7ZUbHBE7JVTB3dQHDg6gfwSKo3hzc)
> 
> However, your code does not consider the rotation difference between two bounding boxes. That is, when calculating IoU, your code assumes the predicted rotation is the same as the ground truth.
> 
> I wonder why the rotation error could be ignored when calculating IoU in evaluation. Thank you very much!



Thank you very much for your attention and interest in our work. You have raised a very good point!

Firstly, the rotation error is indeed significant in 3D object detection/grounding and cannot be ignored. Secondly, we provide the axis-aligned IoU calculation for evaluation to ensure a fair comparison with other baselines. This is because the majority of the baselines do not output rotation angles and can only compute axis-aligned IoU. Third, our method can compute IoU which includes rotation error. We encourage future work to consider rotation error loss and provide new evaluations accordingly.

Thank you again.

**Comment by yfthu** [comment]
> > Thank you for your excellent work!
> > In your code, when evaluating, the IoU calculating is in lib\helpers\tester_helper.py: 213. The calc_iou function is in lib\helpers\utils_helper.py. The calc_iou computes the IoU of two axis-aligned boxes.
> > ![image](https://private-user-images.githubusercontent.com/44047538/336096087-16f9c7ed-c274-40e6-af81-2a5e2b834602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjgxODQsIm5iZiI6MTcxODMyNzg4NCwicGF0aCI6Ii80NDA0NzUzOC8zMzYwOTYwODctMTZmOWM3ZWQtYzI3NC00MGU2LWFmODEtMmE1ZTJiODM0NjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2M2Y3NzVhN2U5YTQ2NWM4MmViMzI3NTliYTE2NjllZWM4MzE4NGE2ZDZkMmU5YWRiZTIyNDI1Y2ZkMDkzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-YVMGQEMJNREypNMPG2_WrWL0_cho6DY1gVPZ1VdmrM)
> > ![image](https://private-user-images.githubusercontent.com/44047538/336095745-9f00e5c1-a40d-4fe3-a4fe-e46e39ebbff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjgxODQsIm5iZiI6MTcxODMyNzg4NCwicGF0aCI6Ii80NDA0NzUzOC8zMzYwOTU3NDUtOWYwMGU1YzEtYTQwZC00ZmUzLWE0ZmUtZTQ2ZTM5ZWJiZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGRjNjZhYTA4YzRlNzg5NGFkMGE2OTIwMDc5ODE0ZGRmNjQzZGFhNjE4ZWRlYWY4M2Y2Nzk4ODkyZGYxNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_09xSdVraMkEz7ZUbHBE7JVTB3dQHDg6gfwSKo3hzc)
> > However, your code does not consider the rotation difference between two bounding boxes. That is, when calculating IoU, your code assumes the predicted rotation is the same as the ground truth.
> > I wonder why the rotation error could be ignored when calculating IoU in evaluation. Thank you very much!
> 
> Thank you very much for your attention and interest in our work. You have raised a very good point!
> 
> Firstly, the rotation error is indeed significant in 3D object detection/grounding and cannot be ignored. Secondly, we provide the axis-aligned IoU calculation for evaluation to ensure a fair comparison with other baselines. This is because the majority of the baselines do not output rotation angles and can only compute axis-aligned IoU. Third, our method can compute IoU which includes rotation error. We encourage future work to consider rotation error loss and provide new evaluations accordingly.
> 
> Thank you again.

Thank you very much for your wonderful work and your patient answer!

**Comment by Matata-Doro** [comment]
> > Thank you for your excellent work!
> > In your code, when evaluating, the IoU calculating is in lib\helpers\tester_helper.py: 213. The calc_iou function is in lib\helpers\utils_helper.py. The calc_iou computes the IoU of two axis-aligned boxes.
> > ![image](https://private-user-images.githubusercontent.com/44047538/336096087-16f9c7ed-c274-40e6-af81-2a5e2b834602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjgxODQsIm5iZiI6MTcxODMyNzg4NCwicGF0aCI6Ii80NDA0NzUzOC8zMzYwOTYwODctMTZmOWM3ZWQtYzI3NC00MGU2LWFmODEtMmE1ZTJiODM0NjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2M2Y3NzVhN2U5YTQ2NWM4MmViMzI3NTliYTE2NjllZWM4MzE4NGE2ZDZkMmU5YWRiZTIyNDI1Y2ZkMDkzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-YVMGQEMJNREypNMPG2_WrWL0_cho6DY1gVPZ1VdmrM)
> > ![image](https://private-user-images.githubusercontent.com/44047538/336095745-9f00e5c1-a40d-4fe3-a4fe-e46e39ebbff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjgxODQsIm5iZiI6MTcxODMyNzg4NCwicGF0aCI6Ii80NDA0NzUzOC8zMzYwOTU3NDUtOWYwMGU1YzEtYTQwZC00ZmUzLWE0ZmUtZTQ2ZTM5ZWJiZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGRjNjZhYTA4YzRlNzg5NGFkMGE2OTIwMDc5ODE0ZGRmNjQzZGFhNjE4ZWRlYWY4M2Y2Nzk4ODkyZGYxNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_09xSdVraMkEz7ZUbHBE7JVTB3dQHDg6gfwSKo3hzc)
> > However, your code does not consider the rotation difference between two bounding boxes. That is, when calculating IoU, your code assumes the predicted rotation is the same as the ground truth.
> > I wonder why the rotation error could be ignored when calculating IoU in evaluation. Thank you very much!
> 
> Thank you very much for your attention and interest in our work. You have raised a very good point!
> 
> Firstly, the rotation error is indeed significant in 3D object detection/grounding and cannot be ignored. Secondly, we provide the axis-aligned IoU calculation for evaluation to ensure a fair comparison with other baselines. This is because the majority of the baselines do not output rotation angles and can only compute axis-aligned IoU. Third, our method can compute IoU which includes rotation error. We encourage future work to consider rotation error loss and provide new evaluations accordingly.
> 
> Thank you again.
还有一个问题是Kitti计算3D框的corners坐标x,y,z对应的应该是l,h,w,你在calc_iou中使用的是h,w,l去计算？
![image](https://github.com/ZhanYang-nwpu/Mono3DVG/assets/170903855/1ebfcd2a-6027-4d96-aa24-5aaa63d09d7f)
